version: "3.9"

services:
# MongoDB services
mongo_db:
  container_name: db_container
  image: mongo:latest
  restart: always 
  volumes: 
  - mongo_db:/data/db

# Node API service
  api:
    build: .
    ports: 
      - 4000:3000
    enviroment:
        PORT: 3000
        MONGO: ${MONGO}     
    depends_on:
      - mongo_db      